//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPRLAB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Armor_on_akk = new HashSet<Armor_on_akk>();
            this.Cheque = new HashSet<Cheque>();
            this.Gun_on_akk = new HashSet<Gun_on_akk>();
        }
    
        public int ID_Account { get; set; }
        public string Account_Name { get; set; }
        public string Login_ { get; set; }
        public string Password_ { get; set; }
        public Nullable<int> Users_ID { get; set; }
        public Nullable<int> Fraction_ID { get; set; }
        public int Role_ID { get; set; }
    
        public virtual Fraction Fraction { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Armor_on_akk> Armor_on_akk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gun_on_akk> Gun_on_akk { get; set; }
    }
}
