//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPRLAB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gun_on_akk
    {
        public int ID_Gun_on_akk { get; set; }
        public int Account_ID { get; set; }
        public int Gun_ID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Guns Guns { get; set; }
    }
}
