//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPRLAB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StalCraftEntities : DbContext
    {
        public StalCraftEntities()
            : base("name=StalCraftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Armor> Armor { get; set; }
        public virtual DbSet<Armor_on_akk> Armor_on_akk { get; set; }
        public virtual DbSet<Cheque> Cheque { get; set; }
        public virtual DbSet<Donate> Donate { get; set; }
        public virtual DbSet<Fraction> Fraction { get; set; }
        public virtual DbSet<Gun_on_akk> Gun_on_akk { get; set; }
        public virtual DbSet<Guns> Guns { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
